swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: apiKey
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{month}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching user transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: apiKey
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add informations in transaction
      description: API for update transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: apiKey
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update informations in transaction
      description: API for update transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: apiKey
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete informations in transaction
      description: API for update transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: apiKey
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      transaction:
        type: object
        properties:
          tranctionId:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: integer
          balance:
            type: integer
          details:
            type: object
            properties:
              transactionType:
                type: string
              category:
                type: string
              notes:
                type: string
  Transactions:
    type: array
    items:
      $ref: "#/definitions/Transaction"
